[project]
name = "dev"
version = "0.1.0"
description = "developement package for ETL"
authors = [
  {name = "Phat Le", email = "phatlebao2@gmail.com"},
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
