# version: '3.8'
name: dev-sample-conda

services:
  my-conda-app:
    build:
      context: .  # Build the Docker image from the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile to use for building the image
    tty: true  # Keep the container running interactively (for debugging purposes)
    volumes:
      - type: volume
        source: dependencies
        target: /opt/miniconda3
    command: >
      /bin/bash -c "
      conda env list &&
      echo 'PATH is $PATH' &&
      tail -f /dev/null"
volumes:
  dependencies:
