name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.11
    - aiosqlite==0.20.0
    - alembic==1.14.0
    - apache-airflow==2.10.4
    - apache-airflow-providers-common-compat==1.3.0
    - apache-airflow-providers-common-io==1.5.0
    - apache-airflow-providers-common-sql==1.21.0
    - apache-airflow-providers-fab==1.5.1
    - apache-airflow-providers-ftp==3.12.0
    - apache-airflow-providers-http==5.0.0
    - apache-airflow-providers-imap==3.8.0
    - apache-airflow-providers-smtp==1.9.0
    - apache-airflow-providers-sqlite==4.0.0
    - apispec==6.8.0
    - argcomplete==3.5.2
    - asgiref==3.8.1
    - attrs==24.3.0
    - blinker==1.9.0
    - cachelib==0.9.0
    - click-plugins==1.1.1
    - clickclick==20.10.2
    - cligj==0.7.2
    - colorlog==6.9.0
    - configupdater==3.2
    - connexion==2.14.2
    - cron-descriptor==1.4.5
    - croniter==6.0.0
    - cython==0.29.36
    - deprecated==1.2.15
    - dnspython==2.7.0
    - email-validator==2.2.0
    - fiona==1.9.4.post1
    - flask-appbuilder==4.5.2
    - flask-babel==2.0.0
    - flask-caching==2.3.0
    - flask-jwt-extended==4.7.1
    - flask-limiter==3.9.2
    - flask-login==0.6.3
    - flask-session==0.5.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==1.2.2
    - fsspec==2024.12.0
    - geographiclib==2.0
    - geopandas==0.13.2
    - geopy==2.4.0
    - google-re2==1.1.20240702
    - googleapis-common-protos==1.66.0
    - grpcio==1.68.1
    - gunicorn==23.0.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - importlib-metadata==8.5.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - limits==3.14.1
    - lockfile==0.12.2
    - loguru==0.7.3
    - mako==1.3.8
    - marshmallow==3.23.2
    - marshmallow-oneofschema==3.1.1
    - marshmallow-sqlalchemy==0.28.2
    - methodtools==0.4.7
    - more-itertools==10.5.0
    - mysql==0.0.3
    - mysqlclient==2.2.6
    - oauthlib==3.2.2
    - opentelemetry-api==1.29.0
    - opentelemetry-exporter-otlp==1.29.0
    - opentelemetry-exporter-otlp-proto-common==1.29.0
    - opentelemetry-exporter-otlp-proto-grpc==1.29.0
    - opentelemetry-exporter-otlp-proto-http==1.29.0
    - opentelemetry-proto==1.29.0
    - opentelemetry-sdk==1.29.0
    - opentelemetry-semantic-conventions==0.50b0
    - ordered-set==4.1.0
    - pandas==1.4.4
    - pendulum==3.0.0
    - pip==24.3.1
    - pluggy==1.5.0
    - prison==0.2.1
    - propcache==0.2.1
    - protobuf==5.29.2
    - pyjwt==2.10.1
    - pylint-venv==2.3.0
    - pymysql==1.1.1
    - pyproj==3.6.0
    - python-daemon==3.1.2
    - python-nvd3==0.16.0
    - qstylizer==0.2.2
    - qtawesome==1.2.2
    - referencing==0.35.1
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - rich-argparse==1.6.0
    - rpds-py==0.22.3
    - scikit-learn==1.2.2
    - setproctitle==1.3.4
    - shapely==2.0.1
    - sqlalchemy-jsonfield==1.0.2
    - sqlalchemy-utils==0.41.2
    - sqlparse==0.5.3
    - termcolor==2.5.0
    - time-machine==2.16.0
    - tweepy==4.14.0
    - universal-pathlib==0.2.6
    - win32-setctime==1.2.0
    - wirerope==0.4.8
    - wtforms==3.2.1
    - yarl==1.18.3
    - zipp==3.21.0
# prefix: C:\Users\PC\anaconda3\envs\env
