name: Test

on: 
  push: 
    branches:
      - main

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        shell: [bash, cmd]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env
          environment-file: environment.yml
          auto-activate-base: false
      
      - name: Display Conda Info
        shell: ${{ matrix.shell }}
        run: |
          conda info
          conda list
      
      - name: Lint Code
        shell: ${{ matrix.shell }}
        run: |
          conda install -y flake8
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run Tests
        shell: ${{ matrix.shell }}
        run: |
          conda install -y pytest
          pytest
